FROM python:3.7-slim

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN python3.7 -m pip install -r requirements.txt

COPY . /app


CMD ["gunicorn", "-w 2", "-b 0.0.0.0:8083", "chatting:app"]
