version: "3"
services:
    db:
        image: mysql:8.0.18
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
          - ./api/db_schemas:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: example
        security_opt:
        - seccomp:unconfined
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8087:8087
        command: docker-php-entrypoint php -S [::]:8087 -t /var/www/html    


    identity:
        image: identity:latest
        tty: true
        stdin_open: true
        ports: 
            - "8081:8081"
        restart: always
        depends_on: 
            - db
        environment: 
            DATABASE_HOST: db
            DATABASE_USER: root
            DATABASE_PASS: example


# networks:
#     internalNetwork:
#         external: false