version: "3"
services:
    db:
        image: mysql:8.0.18
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        volumes:
          - ./api/db_schemas:/docker-entrypoint-initdb.d
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PWD}
        security_opt:
        - seccomp:unconfined
    
    identity:
        image: identity:latest
        tty: true
        stdin_open: true
        ports: 
            - "8081:8081"
        restart: always
        depends_on: 
            - db
